OPTIONS_WIDGET_TYPE:
  full: Full
  kpi-sparkline: Kpi Sparkline
  bar: Bar
  fact: Fact
  pie: Pie
OPTIONS_WIDGET_UNITS:
  '%': Percentage
  $: Currency
  n: Number
  f: Float
  s: Seconds
OPTIONS_DATASET_LABEL:
  '%': Percentage
  $: Currency
  n: Number
  f: Float
  s: Seconds
